# Generated by Django 3.0.6 on 2020-05-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='latitud',
            field=models.IntegerField(default=23, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure',
            name='longitud',
            field=models.IntegerField(default=34, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
